#
# Copyright (C) 2022 Ing <https://github.com/wjz304>
#
# This is free software, licensed under the MIT License.
# See /LICENSE for more information.
#

name: build

on:
  push:
    tags:
      - "*"

  workflow_dispatch:
    inputs:
      spksrc:
        description: "branch"
        required: false
        type: string
      version:
        description: "version"
        required: false
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - "noarch-7.0"

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Init Env
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          sudo timedatectl set-timezone "Asia/Shanghai"

      - name: Install UPX
        uses: crazy-max/ghaction-upx@v4
        with:
          install-only: true

      - name: Calculate version
        id: version
        run: |
          version=""
          if [ ${{ github.ref_type }} == 'tag' ]; then
            version="${{ github.ref_name }}"
          elif [ -n "${{ inputs.version }}" ]; then
            version="${{ inputs.version }}"
          else
            SPK_VERS=$(grep '^SPK_VERS' rr-manager/Makefile | awk -F'=' '{print $2}' | xargs)
            SPK_REV=$(grep '^SPK_REV' rr-manager/Makefile | awk -F'=' '{print $2}' | xargs)
            version="${SPK_VERS:-1.0}${SPK_REV:+-$SPK_REV}"
          fi

          echo "VERSION: ${version}"
          echo "version=${version}" >> $GITHUB_OUTPUT

      - name: Checkout SynoCommunity Source and Docker Image
        run: |
          docker pull ghcr.io/synocommunity/spksrc
          git clone --depth=1 https://github.com/SynoCommunity/spksrc.git

          if [ -n "${{ inputs.spksrc }}" ]; then
            cd spksrc
            git fetch --depth=1 origin "${{ inputs.spksrc }}"
            git checkout "${{ inputs.spksrc }}"
            cd ..
          fi

      - name: Build Package
        run: |
          ROOT_PATH="${{ github.workspace }}"
          MAKE_ARCH="arch-${{ matrix.target }}"

          docker run -v ${ROOT_PATH}/spksrc:/spksrc -v ${ROOT_PATH}/rr-manager:/spksrc/spk/rr-manager -w /spksrc/spk/rr-manager ghcr.io/synocommunity/spksrc make ${MAKE_ARCH}

      - name: Upload to Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.target }}
          path: |
            spksrc/packages/*.spk

      - name: Release
        if: steps.version.outputs.version != ''
        uses: softprops/action-gh-release@v3
        with:
          tag_name: ${{ steps.version.outputs.version }}
          files: spksrc/packages/*.spk
